#!/usr/bin/env python3
"""
release_schedule.py — the PXB1 Phase 1 "Release Schedule Tracker" PRODUCER.

WHY A SCRIPT, NOT THE COWORK/BROWSER FLOW: this report was originally generated by
a Claude Cowork session driving an authenticated Chrome tab (JWT lifted from
localStorage) to hit the YouTrack REST API directly and download a static HTML
file — see the reference recipe this script ports, `~/Downloads/p1release.md`.
That works for an on-demand, human-triggered generation, but the dashboard needs
this report refreshed automatically 3x/day with no browser/LLM in the loop. This
script replicates the exact same business logic using the same YOUTRACK REST API,
but authenticates with a stored permanent token (like scripts/snapshot.py) instead
of a browser session — so it can run unattended in GitHub Actions.

It composes ONE report from the shared engine (core/ytcore.py):
  * epics    — all PXB1 Phase-1 epics (TaskType: EPIC), done and not-done alike.
  * stories  — all PXB1 Phase-1 stories (TaskType: Story), top-level fetch.
  * matching — two-pass story->epic assignment via "Subtask" links (Pass 1: direct
               INWARD link; Pass 2: transitive through an already-mapped parent
               story). Unmatched stories are surfaced as orphans, never dropped.
  * bugs     — for every RE-OPEN story, its open bugs via a "Subtask" then
               "Bugs Reported" OUTWARD link chain (bug drill-down).
  * html     — a standalone report, styled to match the original recipe's output
               byte-for-byte (verbatim CSS/JS lifted from a real generated report).

Output: a single self-contained HTML file (default path: dist/release-schedule.html)
that the calling GitHub Actions workflow publishes to a GitHub Release. The Next.js
UI fetches it server-side via a proxy API route — no Python on Vercel, no token in
the browser.

Run:
    set -a; . ~/.positrack-yt.env; set +a
    python3 scripts/release_schedule.py [--out dist/release-schedule.html]

On any YouTrack 401/403/429 or missing token, this STOPS and prints
"BLOCKED on <reason>" — it never fabricates report data. Exit codes mirror
scripts/snapshot.py's: 3 = missing token, 4 = YouTrack auth/rate-limit error,
5 = any other engine error.

This script runs in CI/local (Python 3.9+), NOT on Vercel, so it may use richer
Python than the stdlib-only engine — but here it stays stdlib-only anyway.
"""
import argparse
import datetime
import html as html_escape_mod
import os
import re
import sys

# Import the shared engine from core/ (canonical) whether we're run from the repo
# root or scripts/. The engine is the SINGLE SOURCE OF TRUTH; we never re-derive
# YouTrack transport, auth, or generic parsing logic that already lives there.
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
for _p in (os.path.join(_ROOT, "core"), _HERE):
    if os.path.isfile(os.path.join(_p, "ytcore.py")):
        sys.path.insert(0, _p)
        break
import ytcore as yt  # noqa: E402

ENGINE_VERSION = "release-schedule-b1"

# ---------------------------------------------------------------- constants
PROJECT = "PXB1"
SCOPE = "PHASE 1"
EXCLUDE_EPIC_IDS = ("PXB1-3295",)  # POS Android — tracked separately, always excluded

# Both cutoffs are recipe constants (~/Downloads/p1release.md) — NOT derived live,
# they mark the last two meetings this report has been generated for.
MEETING_CUTOFF_ISO = "2026-07-03T10:30:00.000Z"   # Jul 3, 4PM IST
JUN29_CUTOFF_ISO = yt.EFFORT_CUTOFF_DEFAULT        # Jun 29, 4PM IST — same constant
                                                    # the Effort Report already uses.

# Reuse the shared engine's pure helpers rather than re-deriving them (avoids two
# "done state" / man-day definitions drifting apart in the same repo).
MAN_DAY = yt.MAN_DAY
is_done_state = yt.is_done_state
iso_to_ms = yt.iso_to_ms

MEETING_CUTOFF_MS = iso_to_ms(MEETING_CUTOFF_ISO)
JUN29_CUTOFF_MS = iso_to_ms(JUN29_CUTOFF_ISO)

# A story in a "re-open"-ish state gets bug drill-down. Same regex ytcore.py's own
# `report(rtype="briefing")` uses to detect reopened states, for consistency.
_REOPEN_RE = re.compile(r"re.?open", re.I)

# The shared ISSUE_FIELDS default has NO `links(...)` clause at all, which would
# silently break two-pass matching if relied on — define our own fields strings
# that request exactly what this report needs, including inline links so matching
# never needs a per-issue N+1 fetch.
_CF_SHAPE = "value(name,fullName,minutes,text)"
EPIC_FIELDS = (
    "idReadable,summary,created,resolved,"
    "customFields(name," + _CF_SHAPE + "),"
    "links(direction,linkType(name),issues(idReadable))"
)
STORY_FIELDS = EPIC_FIELDS  # identical shape; stories need the same fields + links

# Bulk "issue ID: ..." queries are capped by URL length, not YouTrack itself — the
# same chunk size ytcore._child_parent_map uses.
_CHUNK = 80


# ---------------------------------------------------------------- pure field helpers
# Ports of the JS recipe's cf()/cfMin()/cfTs()/cfArr()/maxSprint() helpers. Where the
# shared engine already has an equivalent (estimates, done-state, iso parsing), we
# reuse it directly instead of re-deriving it (see MAN_DAY/is_done_state/iso_to_ms
# above) — these four are the genuinely new pieces this report needs.

def cf_str(issue, name):
    """String presentation of a named custom field (State/Assignee/etc.), via the
    engine's existing name->fullName->login->presentation->text fallback chain."""
    return yt.vname(yt._cf_named(issue, name))


def cf_minutes(issue, name):
    """Minutes from a period-type custom field (Estimation/Spent fields). Wraps
    yt._cf_minutes with a bare-number fallback (the JS recipe's cfMin() is more
    defensive than the engine's dict-only version) rather than re-deriving it."""
    v = yt._cf_named(issue, name)
    if isinstance(v, dict) and v.get("minutes") is not None:
        return int(v["minutes"])
    if isinstance(v, (int, float)):
        return int(v)
    return 0


def cf_timestamp(issue, name):
    """Epoch-ms from a bare-numeric DateIssueCustomField (Deadline Date/QA
    Deadline). No engine equivalent exists — these fields are new to this report."""
    v = yt._cf_named(issue, name)
    return int(v) if isinstance(v, (int, float)) else None


def cf_array(issue, name):
    """List of presentation strings from a multi-value custom field (Sprints)."""
    v = yt._cf_named(issue, name)
    if v is None:
        return []
    if isinstance(v, list):
        return [yt.vname(x) for x in v if yt.vname(x)]
    single = yt.vname(v)
    return [single] if single else []


_SPRINT_NUM_RE = re.compile(r"\d+")


def max_sprint(names):
    """The 'latest' sprint name, sorted by the numeric suffix in its name (e.g.
    beta1-20 > beta1-19), tie-broken alphabetically. None if the list is empty."""
    if not names:
        return None

    def key(nm):
        # The LAST numeric group is the sprint suffix (e.g. "beta1-19" -> 19, not
        # the "1" in "beta1") — a bare .search() would grab the first number.
        matches = _SPRINT_NUM_RE.findall(nm or "")
        return (int(matches[-1]) if matches else 0, nm or "")

    return sorted(set(names), key=key)[-1]


def is_reopen_state(state):
    return bool(_REOPEN_RE.search(state or ""))


# ---------------------------------------------------------------- issue normalization
def _normalize(issue):
    """Recipe-shaped issue -> the flat dict every downstream function operates on.
    Pure; no network. Shared by both epics and stories (same field shape)."""
    return {
        "id": issue.get("idReadable") or "",
        "summary": issue.get("summary") or "",
        "state": cf_str(issue, "State"),
        "assignee": cf_str(issue, "Assignee"),
        "created": issue.get("created"),
        "resolved": issue.get("resolved"),
        "dev_est": cf_minutes(issue, "Server Estimation"),
        "ui_est": cf_minutes(issue, "UI Estimation"),
        "qa_est": cf_minutes(issue, "Testing Estimation"),
        # ASSUMPTION (documented, not verified live — no YT_TOKEN in this dev
        # environment): the built-in "Spent time" period field. ytcore.py notes
        # this field can be inflated by workflow-propagated bug time at the EPIC
        # level; at story level it is what the source recipe's cfMin() reads
        # directly, so we match that rather than introduce a work-item sweep the
        # recipe never used. Verify against a live `describe --project PXB1` if
        # numbers look inflated once real data is available.
        "spent": cf_minutes(issue, "Spent time"),
        "dev_deadline": cf_timestamp(issue, "Deadline Date"),
        "qa_deadline": cf_timestamp(issue, "QA Deadline"),
        "sprints": cf_array(issue, "Sprints"),
        "links": issue.get("links") or [],
    }


# ---------------------------------------------------------------- two-pass matching
def build_story_epic_map(epics, stories):
    """PURE. {story_id: epic_id} via two passes over already-fetched, links-shaped
    dicts (no network — Pass-1/Pass-2 both read `links` inline from the fetch).

    Pass 1: a story with an INWARD "Subtask" link naming a known epic id maps
    directly. Pass 2: iterate to a fixed point over stories Pass-1 left unmapped —
    if a story's INWARD "Subtask" parent is itself a mapped STORY (not an epic),
    the child transitively inherits that story's epic. Anything left after Pass 2
    converges is an orphan — surfaced, never silently dropped.

    Precedence (explicit, since the source recipe's "two-pass" framing doesn't
    state a tie-break rule): Pass 1 always wins; Pass 2 only fills gaps Pass 1
    left. A story is never reassigned once Pass 1 has matched it.
    """
    epic_ids = {e["id"] for e in epics}
    story_ids = {s["id"] for s in stories}
    by_id = {s["id"]: s for s in stories}

    def subtask_parents(issue):
        parents = []
        for lk in issue.get("links") or []:
            if (lk.get("linkType") or {}).get("name") == "Subtask" and lk.get("direction") == "INWARD":
                for p in lk.get("issues") or []:
                    pid = p.get("idReadable")
                    if pid:
                        parents.append(pid)
        return parents

    mapping = {}
    unmapped = []
    for s in stories:
        parents = subtask_parents(s)
        direct_epic = next((p for p in parents if p in epic_ids), None)
        if direct_epic:
            mapping[s["id"]] = direct_epic
        else:
            unmapped.append(s["id"])

    # Pass 2: iterate to a fixed point — a grandparent-story chain is plausible.
    changed = True
    while changed and unmapped:
        changed = False
        still_unmapped = []
        for sid in unmapped:
            story = by_id.get(sid)
            parents = subtask_parents(story) if story else []
            parent_epic = next(
                (mapping[p] for p in parents if p in story_ids and p in mapping), None,
            )
            if parent_epic:
                mapping[sid] = parent_epic
                changed = True
            else:
                still_unmapped.append(sid)
        unmapped = still_unmapped

    orphan_story_ids = unmapped
    return mapping, orphan_story_ids


# ---------------------------------------------------------------- bug drilldown
def _children_by_parent(ctx, parent_ids, link_name, chunk=_CHUNK):
    """{parent_id: [child_id, ...]} for the OUTWARD `link_name` children of
    `parent_ids`, via a CHUNKED `issue ID: ...` bulk query (no N+1). Generalizes
    ytcore._child_parent_map's query shape but returns the inverted, list-valued
    mapping this report needs — reused for BOTH bug-drilldown hops by parameter."""
    out = {}
    ids = [i for i in parent_ids if i]
    for start in range(0, len(ids), chunk):
        batch = ids[start:start + chunk]
        q = "issue ID: " + ", ".join(batch)
        issues = yt.get_issues(
            ctx, q, fields="idReadable,links(direction,linkType(name),issues(idReadable))", top=300,
        )
        for it in issues:
            pid = it.get("idReadable")
            for lk in it.get("links") or []:
                if (lk.get("linkType") or {}).get("name") == link_name and lk.get("direction") == "OUTWARD":
                    for c in lk.get("issues") or []:
                        cid = c.get("idReadable")
                        if cid:
                            out.setdefault(pid, [])
                            if cid not in out[pid]:
                                out[pid].append(cid)
    return out


def bug_drilldown(ctx, reopen_story_ids):
    """{story_id: [{"id","summary","state"}, ...]} of OPEN bugs only, reached via
    RE-OPEN story -> "Subtask" OUTWARD (dev ticket) -> "Bugs Reported" OUTWARD
    (bug). Two chunked bulk-link lookups + one chunked detail fetch — no N+1
    regardless of how many RE-OPEN stories exist."""
    if not reopen_story_ids:
        return {}
    story_to_tickets = _children_by_parent(ctx, reopen_story_ids, "Subtask")
    all_tickets = sorted({t for tickets in story_to_tickets.values() for t in tickets})
    if not all_tickets:
        return {}
    ticket_to_bugs = _children_by_parent(ctx, all_tickets, "Bugs Reported")
    all_bug_ids = sorted({b for bugs in ticket_to_bugs.values() for b in bugs})
    if not all_bug_ids:
        return {}

    bug_details = {}
    for start in range(0, len(all_bug_ids), _CHUNK):
        batch = all_bug_ids[start:start + _CHUNK]
        q = "issue ID: " + ", ".join(batch)
        for it in yt.get_issues(ctx, q, fields="idReadable,summary,customFields(name,value(name))", top=300):
            bug_details[it.get("idReadable")] = {
                "id": it.get("idReadable"),
                "summary": it.get("summary") or "",
                "state": cf_str(it, "State"),
            }

    result = {}
    for sid, tickets in story_to_tickets.items():
        bugs = []
        for t in tickets:
            for bid in ticket_to_bugs.get(t, []):
                bug = bug_details.get(bid)
                if bug and not is_done_state(bug["state"]):  # "open" = not done/resolved
                    bugs.append(bug)
        if bugs:
            result[sid] = bugs
    return result


# ---------------------------------------------------------------- per-epic computation
def epic_state_badge(all_stories, epic_own_state):
    """(display_text, is_done) for an epic's state badge.
      * zero stories  -> the epic's own State field, not derived from children.
      * exactly 1 story -> that story's literal state text (not "DONE"/"NOT DONE").
      * all done      -> ("DONE", True)
      * any pending   -> ("NOT DONE", False)
    """
    if not all_stories:
        return epic_own_state or "—", is_done_state(epic_own_state)
    if len(all_stories) == 1:
        s = all_stories[0]
        return s["state"] or "—", is_done_state(s["state"])
    all_done = all(is_done_state(s["state"]) for s in all_stories)
    return ("DONE" if all_done else "NOT DONE"), all_done


def visible_stories(epic_done, all_stories):
    """Story Visibility Rules (verbatim from the recipe):
      NOT DONE epic -> pending stories + stories done after the MEETING cutoff.
      DONE epic     -> only stories resolved after the JUN29 cutoff.
    Cutoff boundary is EXCLUSIVE ("after X"), i.e. strictly greater-than."""
    if epic_done:
        return [
            s for s in all_stories
            if s["resolved"] is not None and s["resolved"] > JUN29_CUTOFF_MS
        ]
    out = []
    for s in all_stories:
        if not is_done_state(s["state"]):
            out.append(s)
        elif s["resolved"] is not None and s["resolved"] > MEETING_CUTOFF_MS:
            out.append(s)
    return out


def epic_rollup(epic_done, all_stories, visible):
    """Estimates/Spent/Sprint rollup at epic level (verbatim from the recipe):
      NOT DONE epics -> from PENDING stories only (a stricter subset than
                        "visible", which also includes done-after-meeting stories).
      DONE epics     -> from the visible (resolved-after-Jun29) stories."""
    pool = visible if epic_done else [s for s in all_stories if not is_done_state(s["state"])]
    sprints = max_sprint([sp for s in pool for sp in s["sprints"]])
    return {
        "dev": sum(s["dev_est"] for s in pool),
        "ui": sum(s["ui_est"] for s in pool),
        "qa": sum(s["qa_est"] for s in pool),
        "spent": sum(s["spent"] for s in pool),
        "sprint": sprints,
    }


def epic_resolved_date(epic_done, visible):
    """Max resolved date across visible stories — only meaningful when the epic is
    DONE (per the recipe: 'only shown when epicState === DONE')."""
    if not epic_done:
        return None
    dates = [s["resolved"] for s in visible if s["resolved"] is not None]
    return max(dates) if dates else None


# ---------------------------------------------------------------- milestone grouping
_DAY_MS = 86400000


def milestone_key(epic):
    """max(Dev Deadline, QA Deadline) for one epic, bucketed by CALENDAR DAY (not
    exact-ms equality) so same-day deadlines a few minutes apart still group
    together. None (both deadlines missing) -> the caller buckets these last,
    surfaced as their own group rather than silently dropped."""
    candidates = [d for d in (epic.get("dev_deadline"), epic.get("qa_deadline")) if d is not None]
    if not candidates:
        return None
    ts = max(candidates)
    return (ts // _DAY_MS) * _DAY_MS


def group_by_milestone(epics):
    """[{"date_ms": int|None, "epics": [...], "all_done": bool}, ...] sorted
    ascending, with the no-deadline bucket (date_ms=None) sorted LAST."""
    buckets = {}
    for e in epics:
        key = milestone_key(e)
        buckets.setdefault(key, []).append(e)

    def sort_key(k):
        return (k is None, k if k is not None else 0)

    groups = []
    for key in sorted(buckets, key=sort_key):
        group_epics = buckets[key]
        all_done = all(e["_epic_done"] for e in group_epics)
        groups.append({"date_ms": key, "epics": group_epics, "all_done": all_done})
    return groups


# ---------------------------------------------------------------- compose (network)
def _fetch_epics(ctx):
    q = "project: %s TaskType: EPIC Scope: {%s}" % (PROJECT, SCOPE)
    raw = yt.get_issues(ctx, q, fields=EPIC_FIELDS, top=300)
    exclude = set(EXCLUDE_EPIC_IDS)
    return [_normalize(e) for e in raw if e.get("idReadable") not in exclude]


def _fetch_stories(ctx):
    # Top-level fetch, per the recipe's explicit warning that stories nested under
    # an epic do not reliably return fully-resolved customFields.
    q = "project: %s Scope: {%s} TaskType: Story" % (PROJECT, SCOPE)
    raw = yt.get_issues(ctx, q, fields=STORY_FIELDS, top=300)
    return [_normalize(s) for s in raw]


def build_report_data(ctx):
    epics = _fetch_epics(ctx)
    stories = _fetch_stories(ctx)

    story_epic_map, orphan_story_ids = build_story_epic_map(epics, stories)
    stories_by_epic = {}
    for s in stories:
        eid = story_epic_map.get(s["id"])
        if eid:
            stories_by_epic.setdefault(eid, []).append(s)

    reopen_story_ids = [s["id"] for s in stories if is_reopen_state(s["state"])]
    bugs_by_story = bug_drilldown(ctx, reopen_story_ids)

    for e in epics:
        all_stories = stories_by_epic.get(e["id"], [])
        badge_text, epic_done = epic_state_badge(all_stories, e["state"])
        visible = visible_stories(epic_done, all_stories)
        e["_all_stories"] = all_stories
        e["_visible_stories"] = visible
        e["_epic_state_badge"] = badge_text
        e["_epic_done"] = epic_done
        e["_resolved_date"] = epic_resolved_date(epic_done, visible)
        e["_rollup"] = epic_rollup(epic_done, all_stories, visible)

    milestones = group_by_milestone(epics)

    total_pending_epics = sum(1 for e in epics if not e["_epic_done"])
    totals = {
        "dev": sum(e["_rollup"]["dev"] for e in epics),
        "ui": sum(e["_rollup"]["ui"] for e in epics),
        "qa": sum(e["_rollup"]["qa"] for e in epics),
        "spent": sum(e["_rollup"]["spent"] for e in epics),
        "epics_total": len(epics),
        "epics_done": len(epics) - total_pending_epics,
        "epics_pending": total_pending_epics,
        "stories_total": len(stories),
        "stories_done": sum(1 for s in stories if is_done_state(s["state"])),
        "stories_pending": sum(1 for s in stories if not is_done_state(s["state"])),
        "open_bugs": sum(len(v) for v in bugs_by_story.values()),
        "reopen_stories": sum(1 for sid in bugs_by_story if sid in reopen_story_ids),
    }
    totals["total_est"] = totals["dev"] + totals["ui"] + totals["qa"]
    totals["remaining"] = max(0, totals["total_est"] - totals["spent"])

    final_ts = max(
        (m["date_ms"] for m in milestones if m["date_ms"] is not None), default=None,
    )

    return {
        "generated_at_iso": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "project": PROJECT,
        "scope": SCOPE,
        "engine_version": ENGINE_VERSION,
        "milestones": milestones,
        "orphan_story_ids": orphan_story_ids,
        "bugs_by_story": bugs_by_story,
        "totals": totals,
        "final_ts": final_ts,
        "milestone_count": len([m for m in milestones if m["date_ms"] is not None]),
    }


# ---------------------------------------------------------------- HTML rendering
# Verbatim CSS/JS lifted from a real generated report (see module docstring) so
# styling is reused byte-for-byte rather than reconstructed from a description.
CSS = (
    "*{box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:13px;margin:0;"
    "background:#f1f5f9;color:#0f172a}.hdr{background:#0f172a;color:#fff}"
    ".hdr-top{padding:16px 24px 12px;border-bottom:3px solid #3b82f6}"
    ".hdr h1{margin:0;font-size:20px;font-weight:800}.hdr p{margin:3px 0 0;font-size:11px;opacity:.6}"
    ".totals-band{background:#0f172a;display:flex;flex-wrap:wrap;border-bottom:3px solid #1e293b}"
    ".tb{flex:1;min-width:110px;padding:14px 16px;border-right:1px solid #1e293b;text-align:center}"
    ".tb:last-child{border-right:none}"
    ".tb-lbl{font-size:9px;text-transform:uppercase;letter-spacing:.7px;color:#94a3b8;margin-bottom:5px}"
    ".tb-h{font-size:22px;font-weight:800;line-height:1;margin-bottom:2px}"
    ".tb-md{font-size:11px;font-weight:600}"
    ".final-banner{background:linear-gradient(135deg,#1e3a8a,#4c1d95);color:#fff;padding:14px 24px;"
    "display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:16px}"
    ".final-date{font-size:20px;font-weight:800}"
    ".stat-grp{display:flex;flex-direction:column;gap:6px}"
    ".stat-grp-lbl{font-size:9px;text-transform:uppercase;letter-spacing:.7px;opacity:.8;font-weight:700}"
    ".stat-row{display:flex;gap:16px;flex-wrap:wrap}.stat-box{text-align:center;min-width:52px}"
    ".stat-val{font-size:26px;font-weight:800;line-height:1}"
    ".stat-lbl{font-size:9px;opacity:.65;margin-top:2px;white-space:nowrap}"
    ".legend{display:flex;gap:10px;margin:10px 20px 4px;flex-wrap:wrap;align-items:center;font-size:10px;"
    "color:#64748b}.leg{display:flex;align-items:center;gap:4px}"
    ".led{width:10px;height:10px;border-radius:2px;flex-shrink:0}.dg{margin:10px 20px 0}"
    ".dh{display:flex;align-items:center;padding:11px 16px;border-radius:8px 8px 0 0;color:#fff;"
    "cursor:pointer;flex-wrap:wrap;gap:8px;font-size:16px;font-weight:800}"
    ".cnt{background:rgba(255,255,255,.22);border-radius:12px;padding:2px 10px;font-size:11px;font-weight:700}"
    "table td{padding:7px 9px;border-bottom:1px solid #f1f5f9;vertical-align:middle;color:#0f172a}"
    "table th{color:#fff;padding:8px 9px;text-align:left;font-size:11px;white-space:nowrap;font-weight:600}"
    ".footer{background:#0f172a;color:#fff;padding:14px 24px;margin:14px 20px 36px;border-radius:8px;"
    "font-size:12px;display:flex;flex-wrap:wrap;gap:12px;align-items:center;line-height:2}"
    ".hi{font-size:15px;font-weight:800}"
)
JS = (
    'function ts(id){var el=document.getElementById(id);if(el)el.style.display='
    'el.style.display==="none"?"":"none";}'
    'function tg(cls){document.querySelectorAll("."+cls).forEach(function(el){'
    'el.style.display=el.style.display==="none"?"":"none";});}'
)

_MILESTONE_COLORS = [
    (0, "#7f1d1d"),   # overdue
    (3, "#b91c1c"),   # <=3d
    (7, "#c2410c"),   # <=7d
    (14, "#b45309"),  # <=14d
    (None, "#15803d"),  # >14d
]


def _esc(s):
    return html_escape_mod.escape(str(s or ""), quote=True)


def _fmt_h(minutes):
    return "%.1fh" % (minutes / 60.0)


def _fmt_md(minutes):
    return "%.1f md" % (minutes / float(MAN_DAY))


def datetime_from_ms(ms):
    return datetime.datetime.fromtimestamp(ms / 1000.0, tz=datetime.timezone.utc)


def _fmt_date(ms, fmt="%d %b"):
    if ms is None:
        return ""
    return datetime_from_ms(ms).strftime(fmt)


def _milestone_color(date_ms, now_ms, all_done):
    if all_done:
        return "#166534"
    if date_ms is None:
        return "#334155"  # neutral slate for the "no deadline" bucket
    days = (date_ms - now_ms) / _DAY_MS
    for threshold, color in _MILESTONE_COLORS:
        if threshold is None or days <= threshold:
            return color
    return "#15803d"


def render_story_row(story, bugs, row_id):
    resolved_html = ""
    if story["resolved"] is not None:
        resolved_html = '<b style="font-size:11px">%s</b>' % _fmt_date(story["resolved"])
    bug_btn = ""
    if bugs:
        bug_btn = (
            '<button onclick="tg(\'bugs_%s\')" style="background:#7f1d1d;color:#fff;border:none;'
            'border-radius:3px;cursor:pointer;font-size:9px;padding:2px 6px;margin-left:3px">'
            '\U0001f41b %d bug%s</button>'
        ) % (row_id, len(bugs), "" if len(bugs) == 1 else "s")
    # Built as a list of the 12 <td> cells (matching _TABLE_HEAD's column order
    # exactly: Epic/Story, Summary, State, Assignee, Dev/UI/QA Est, Spent,
    # Dev/QA Deadline, Resolved, Sprint) rather than one long %-format string —
    # a prior version of this row silently dropped the QA Deadline cell and
    # threw a "not enough arguments" error from manual placeholder counting.
    cells = [
        '<td style="padding:6px 9px 6px 28px;white-space:nowrap">'
        '<a href="https://support.posibolt.com/issue/%s" target="_blank" '
        'style="font-weight:700;color:#0f172a;font-size:11px;text-decoration:none">%s</a>%s</td>'
        % (_esc(story["id"]), _esc(story["id"]), bug_btn),
        '<td style="font-size:11px;padding:6px 9px">%s</td>' % _esc(story["summary"]),
        '<td style="padding:6px 9px"><span style="font-size:9px;padding:1px 6px;'
        'border-radius:10px;background:#e2e8f0">%s</span></td>' % _esc(story["state"]),
        '<td style="font-size:11px;padding:6px 9px">%s</td>' % _esc(story["assignee"]),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % _fmt_h(story["dev_est"]),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % _fmt_h(story["ui_est"]),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % _fmt_h(story["qa_est"]),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % _fmt_h(story["spent"]),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % (_fmt_date(story["dev_deadline"]) or "—"),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % (_fmt_date(story["qa_deadline"]) or "—"),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % (resolved_html or "—"),
        '<td style="text-align:center;padding:6px 9px">%s</td>' % _esc(max_sprint(story["sprints"]) or ""),
    ]
    row = '<tr class="sr sr_%s" style="display:none;background:#f7fff7">%s</tr>' % (
        row_id, "".join(cells),
    )
    if bugs:
        bug_rows = "".join(
            '<tr class="bugs_%s" style="display:none;background:#fff5f5">'
            '<td colspan="12" style="padding:4px 9px 4px 48px">'
            '<a href="https://support.posibolt.com/issue/%s" target="_blank" '
            'style="color:#b91c1c;font-weight:700;text-decoration:none;font-size:10.5px">%s</a>'
            ' <span style="font-size:10.5px;color:#475569">%s</span>'
            ' <span style="font-size:9px;background:#fee2e2;color:#b91c1c;padding:1px 5px;'
            'border-radius:3px;margin-left:4px">%s</span></td></tr>'
            % (row_id, _esc(b["id"]), _esc(b["id"]), _esc(b["summary"]), _esc(b["state"]))
            for b in bugs
        )
        row += bug_rows
    return row


def render_epic_row(epic, bugs_by_story):
    r = epic["_rollup"]
    done = epic["_epic_done"]
    border_color = "#22c55e" if done else "#ef4444"
    bg = "#f0fff4" if done else "#fff8f8"
    badge_bg, badge_fg = ("#dcfce7", "#15803d") if done else ("#fee2e2", "#b91c1c")
    badge_text = epic["_epic_state_badge"]

    visible = epic["_visible_stories"]
    expand_btn = ""
    story_rows_html = ""
    if visible:
        row_id = "sr_%s" % epic["id"].replace("-", "_")
        n_done = sum(1 for s in visible if is_done_state(s["state"]))
        label = "%d %s story" % (
            len(visible), "done" if n_done == len(visible) else "linked",
        )
        expand_btn = (
            '<button onclick="tg(\'%s\')" style="background:%s;color:#fff;border:none;'
            'border-radius:3px;cursor:pointer;font-size:9px;padding:2px 6px;margin-left:3px">'
            "▶ %s%s</button>"
        ) % (row_id, "#15803d" if done else "#334155", label, "" if len(visible) == 1 else "s")
        story_rows_html = "".join(
            render_story_row(s, bugs_by_story.get(s["id"], []), "%s_%d" % (row_id, i))
            for i, s in enumerate(visible)
        )

    resolved_cell = "—"
    if epic["_resolved_date"] is not None and epic["dev_deadline"] is not None:
        color = "#15803d" if epic["_resolved_date"] <= epic["dev_deadline"] else "#b91c1c"
        resolved_cell = '<b style="font-size:11px;color:%s">%s</b>' % (
            color, _fmt_date(epic["_resolved_date"]),
        )
    elif epic["_resolved_date"] is not None:
        resolved_cell = '<b style="font-size:11px">%s</b>' % _fmt_date(epic["_resolved_date"])

    row = (
        '<tr style="background:%s;border-left:4px solid %s;border-bottom:2px solid %s">'
        '<td style="white-space:nowrap;padding:8px 9px">'
        '<a href="https://support.posibolt.com/issue/%s" target="_blank" '
        'style="font-weight:800;color:#0f172a;font-size:12px;text-decoration:none">%s</a>%s</td>'
        '<td style="font-size:12px;font-weight:600;max-width:260px;padding:8px 9px">%s</td>'
        '<td style="padding:8px 9px"><span style="background:%s;color:%s;font-size:9px;'
        'padding:1px 6px;border-radius:10px;font-weight:700">%s</span></td>'
        '<td style="font-size:11px;color:#374151;white-space:nowrap;padding:8px 9px">%s</td>'
        '<td style="text-align:center;padding:6px 9px">%s</td>'
        '<td style="text-align:center;padding:6px 9px">%s</td>'
        '<td style="text-align:center;padding:6px 9px">%s</td>'
        '<td style="text-align:center;padding:6px 9px">%s</td>'
        '<td style="text-align:center;padding:8px 9px;white-space:nowrap"><b style="color:#1d4ed8;'
        'font-size:12px">%s</b></td>'
        '<td style="text-align:center;padding:8px 9px;white-space:nowrap"><b style="color:#15803d;'
        'font-size:12px">%s</b></td>'
        '<td style="text-align:center;padding:6px 9px">%s</td>'
        '<td style="text-align:center;padding:8px 9px"><span style="background:#ede9fe;color:#5b21b6;'
        'font-size:9px;padding:1px 5px;border-radius:3px;font-weight:600">%s</span></td>'
        "</tr>%s"
    ) % (
        bg, border_color, border_color,
        _esc(epic["id"]), _esc(epic["id"]), expand_btn,
        _esc(epic["summary"]),
        badge_bg, badge_fg, _esc(badge_text),
        _esc(epic["assignee"]),
        _fmt_h(r["dev"]), _fmt_h(r["ui"]), _fmt_h(r["qa"]), _fmt_h(r["spent"]),
        _fmt_date(epic["dev_deadline"]) or "—",
        _fmt_date(epic["qa_deadline"]) or "—",
        resolved_cell,
        _esc(r["sprint"] or ""),
        story_rows_html,
    )
    return row


_TABLE_HEAD = (
    '<tr style="background:#1e293b;color:#fff">'
    '<th style="min-width:95px">Epic / Story</th><th style="min-width:200px">Summary</th>'
    '<th style="min-width:120px">State</th><th style="min-width:100px">Assignee</th>'
    '<th style="text-align:center;min-width:75px">Dev Est</th>'
    '<th style="text-align:center;min-width:65px">UI Est</th>'
    '<th style="text-align:center;min-width:65px">QA Est</th>'
    '<th style="text-align:center;min-width:65px">Spent</th>'
    '<th style="text-align:center;min-width:85px">Dev Deadline</th>'
    '<th style="text-align:center;min-width:85px">QA Deadline</th>'
    '<th style="text-align:center;min-width:90px">Resolved</th>'
    '<th style="text-align:center;min-width:80px">Sprint</th></tr>'
)


def render_milestone_group(group, bugs_by_story, now_ms, index):
    date_ms = group["date_ms"]
    all_done = group["all_done"]
    color = _milestone_color(date_ms, now_ms, all_done)
    if date_ms is None:
        label = "\U0001f4c5 No deadline set"
    else:
        icon = "✅" if all_done else "\U0001f4c5"
        label = "%s %s" % (icon, _fmt_date(date_ms, "%a, %d %b %Y"))
    n_epics = len(group["epics"])
    n_stories = sum(len(e["_visible_stories"]) for e in group["epics"])
    group_id = "grp_%d" % index
    rows = "".join(render_epic_row(e, bugs_by_story) for e in group["epics"])
    return (
        '<div class="dg"><div class="dh" style="background:%s" onclick="ts(\'%s\')">%s '
        '<span class="cnt">%d epic%s</span><span class="cnt">%d stor%s</span></div>'
        '<div id="%s" style="overflow-x:auto;background:#fff;border:1px solid #e2e8f0;'
        'border-top:none;border-radius:0 0 6px 6px"><table style="width:100%%;'
        'border-collapse:collapse">%s%s</table></div></div>'
    ) % (
        color, group_id, label,
        n_epics, "" if n_epics == 1 else "s",
        n_stories, "y" if n_stories == 1 else "ies",
        group_id, _TABLE_HEAD, rows,
    )


def render_html(data):
    t = data["totals"]
    now = datetime.datetime.now(tz=datetime.timezone.utc)
    now_ms = int(now.timestamp() * 1000)
    generated_disp = now.strftime("%d %b %Y, %H:%M")

    final_banner = ""
    if data["final_ts"] is not None:
        final_dt = datetime_from_ms(data["final_ts"])
        days_out = max(0, (data["final_ts"] - now_ms) // _DAY_MS)
        final_banner = (
            '<div class="final-banner"><div>'
            '<div style="font-size:9px;text-transform:uppercase;letter-spacing:.8px;opacity:.7;'
            'margin-bottom:4px">\U0001f3c1 Final Completion Date</div>'
            '<div class="final-date">%s</div>'
            '<div style="font-size:11px;margin-top:5px;opacity:.75">%dd from today &nbsp;·&nbsp; '
            "%d milestones</div></div>"
            '<div class="stat-grp"><div class="stat-grp-lbl">Epics</div><div class="stat-row">'
            '<div class="stat-box"><div class="stat-val">%d</div><div class="stat-lbl">Total</div></div>'
            '<div class="stat-box"><div class="stat-val" style="color:#4ade80">%d</div>'
            '<div class="stat-lbl">Done</div></div>'
            '<div class="stat-box"><div class="stat-val" style="color:#fca5a5">%d</div>'
            "<div class=\"stat-lbl\">Pending</div></div></div></div>"
            '<div class="stat-grp" style="border-left:1px solid rgba(255,255,255,.15);'
            'padding-left:20px"><div class="stat-grp-lbl">Stories</div><div class="stat-row">'
            '<div class="stat-box"><div class="stat-val">%d</div><div class="stat-lbl">Total</div></div>'
            '<div class="stat-box"><div class="stat-val" style="color:#4ade80">%d</div>'
            '<div class="stat-lbl">Done</div></div>'
            '<div class="stat-box"><div class="stat-val" style="color:#fca5a5">%d</div>'
            "<div class=\"stat-lbl\">Pending</div></div></div></div>"
            '<div class="stat-grp" style="border-left:1px solid rgba(255,255,255,.15);'
            'padding-left:20px;background:rgba(153,27,27,.3);padding:10px 16px;border-radius:8px;'
            'margin-left:4px"><div class="stat-grp-lbl" style="color:#fca5a5">\U0001f41b Open Bugs</div>'
            '<div class="stat-row"><div class="stat-box"><div class="stat-val" style="color:#fca5a5">%d</div>'
            '<div class="stat-lbl">Open Bugs</div></div>'
            '<div class="stat-box"><div class="stat-val" style="color:#fca5a5">%d</div>'
            "<div class=\"stat-lbl\">RE-OPEN Stories</div></div></div></div></div>"
        ) % (
            final_dt.strftime("%A, %d %b %Y"), days_out, data["milestone_count"],
            t["epics_total"], t["epics_done"], t["epics_pending"],
            t["stories_total"], t["stories_done"], t["stories_pending"],
            t["open_bugs"], t["reopen_stories"],
        )

    groups_html = "".join(
        render_milestone_group(g, data["bugs_by_story"], now_ms, i)
        for i, g in enumerate(data["milestones"])
    )

    orphan_html = (
        '<span class="hi">%d</span> orphan stor%s with no epic match '
        "(excluded from milestones, not silently dropped)."
        % (len(data["orphan_story_ids"]), "y" if len(data["orphan_story_ids"]) == 1 else "ies")
    ) if data["orphan_story_ids"] else "All stories matched to an epic."

    body = (
        '<div class="hdr"><div class="hdr-top"><h1>PXB1 Phase 1 — Release Schedule '
        "(Meeting Tracking)</h1><p>Generated %s UTC &nbsp;·&nbsp; Dev Est = Server Est "
        "· QA Est = Testing Est</p></div>"
        '<div class="totals-band">'
        '<div class="tb"><div class="tb-lbl">Dev (Server) Est</div>'
        '<div class="tb-h" style="color:#c4b5fd">%s</div><div class="tb-md" style="color:#7c3aed">%s</div></div>'
        '<div class="tb"><div class="tb-lbl">UI Est</div>'
        '<div class="tb-h" style="color:#f9a8d4">%s</div><div class="tb-md" style="color:#db2777">%s</div></div>'
        '<div class="tb"><div class="tb-lbl">QA (Testing) Est</div>'
        '<div class="tb-h" style="color:#67e8f9">%s</div><div class="tb-md" style="color:#0891b2">%s</div></div>'
        '<div class="tb" style="background:#162032"><div class="tb-lbl">Total Estimate</div>'
        '<div class="tb-h" style="color:#fde68a">%s</div><div class="tb-md" style="color:#f59e0b">%s</div></div>'
        '<div class="tb"><div class="tb-lbl">Spent So Far</div>'
        '<div class="tb-h" style="color:#6ee7b7">%s</div><div class="tb-md" style="color:#059669">%s</div></div>'
        '<div class="tb" style="background:#162032"><div class="tb-lbl">Remaining</div>'
        '<div class="tb-h" style="color:#fca5a5">%s</div><div class="tb-md" style="color:#dc2626">%s</div></div>'
        '<div class="tb"><div class="tb-lbl">Epics Done</div>'
        '<div class="tb-h" style="color:#4ade80">%d</div><div class="tb-md" style="color:#16a34a">of %d</div></div>'
        "</div></div>%s"
        '<div class="legend">'
        '<span class="leg"><span class="led" style="background:#166534"></span>All done</span>'
        '<span class="leg"><span class="led" style="background:#7f1d1d"></span>Overdue</span>'
        '<span class="leg"><span class="led" style="background:#b91c1c"></span>≤3d</span>'
        '<span class="leg"><span class="led" style="background:#c2410c"></span>≤7d</span>'
        '<span class="leg"><span class="led" style="background:#b45309"></span>≤14d</span>'
        '<span class="leg"><span class="led" style="background:#15803d"></span>&gt;14d</span>'
        "</div>%s"
        '<div class="footer">%s</div>'
    ) % (
        generated_disp,
        _fmt_h(t["dev"]), _fmt_md(t["dev"]),
        _fmt_h(t["ui"]), _fmt_md(t["ui"]),
        _fmt_h(t["qa"]), _fmt_md(t["qa"]),
        _fmt_h(t["total_est"]), _fmt_md(t["total_est"]),
        _fmt_h(t["spent"]), _fmt_md(t["spent"]),
        _fmt_h(t["remaining"]), _fmt_md(t["remaining"]),
        t["epics_done"], t["epics_total"],
        final_banner,
        groups_html,
        orphan_html,
    )

    return (
        "<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
        "<title>PXB1 Phase 1 Release Schedule</title><style>%s</style></head>"
        "<body>%s<script>%s</script></body></html>"
    ) % (CSS, body, JS)


# ---------------------------------------------------------------- CLI
def main(argv=None):
    ap = argparse.ArgumentParser(description="PXB1 Phase 1 Release Schedule Tracker producer")
    ap.add_argument("--project", default=PROJECT)
    ap.add_argument("--scope", default=SCOPE)
    ap.add_argument("--base", default="", help="YouTrack base URL override")
    ap.add_argument("--out", default="dist/release-schedule.html")
    a = ap.parse_args(argv)

    token = os.environ.get("YT_TOKEN", "").strip()
    if not token:
        print("BLOCKED on missing token: set $YT_TOKEN (e.g. `set -a; . ~/.positrack-yt.env; set +a`).",
              file=sys.stderr)
        return 3

    ctx = yt.Ctx(token, a.base or os.environ.get("YT_BASE") or yt.DEFAULT_BASE)
    try:
        yt.whoami(ctx)
        data = build_report_data(ctx)
    except yt.YTError as e:
        code = e.status_code
        if code in (401, 403, 429):
            print("BLOCKED on YouTrack %s: %s" % (code, e.friendly_message), file=sys.stderr)
            return 4
        print("BLOCKED on engine error: %s" % e.friendly_message, file=sys.stderr)
        return 5

    html_out = render_html(data)
    out_dir = os.path.dirname(a.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(html_out)

    t = data["totals"]
    print(
        "release-schedule: %d epics (%d done / %d pending), %d stories, "
        "%d milestones, %d orphan stories, %d open bugs -> %s"
        % (
            t["epics_total"], t["epics_done"], t["epics_pending"], t["stories_total"],
            data["milestone_count"], len(data["orphan_story_ids"]), t["open_bugs"], a.out,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
